#!/usr/bin/env python3
"""forge stage: generate _headers, with a CSP whose script-src names index.html's
own inline scripts by hash.

Fathom is a single file with inline scripts by design, and `script-src 'self'`
blocks exactly those. The honest fix is neither 'unsafe-inline' nor a nonce (a
static origin cannot mint one) but the scripts' SHA-256 hashes -- which means
they must be regenerated whenever the page's scripts change. `make headers`
does that; `forge/test/csp.spec.js` fails if _headers is stale.
"""
import base64
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PAGE = ROOT / "index.html"
OUT = ROOT / "_headers"


def hashes(html):
    """Every inline <script>'s CSP hash, in document order."""
    out = []
    for m in re.finditer(r"<script(?![^>]*\ssrc=)[^>]*>(.*?)</script>", html, re.S):
        digest = hashlib.sha256(m.group(1).encode()).digest()
        out.append("'sha256-" + base64.b64encode(digest).decode() + "'")
    return out


def render(hs):
    csp = (
        "default-src 'self'; "
        f"script-src 'self' 'wasm-unsafe-eval' {' '.join(hs)}; "
        "worker-src 'self'; "
        "style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data:; "
        "font-src 'self'; "
        "connect-src 'self'; "
        "object-src 'none'; "
        "base-uri 'none'; "
        "frame-ancestors 'none'"
    )
    return (
        "# Generated by forge/deploy/headers.py -- do not edit.\n"
        "# The script hashes are index.html's own inline scripts; regenerate with `make headers`.\n"
        "/*\n"
        f"  Content-Security-Policy: {csp}\n"
        "  X-Content-Type-Options: nosniff\n"
        "  Referrer-Policy: no-referrer\n"
    )


def main():
    hs = hashes(PAGE.read_text())
    if not hs:
        print("TOOLCHAIN: no inline scripts found in index.html")
        sys.exit(2)
    text = render(hs)
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print("STALE: _headers does not match index.html's inline scripts")
            print("  remedy: make headers")
            sys.exit(1)
        print(f"OK  _headers matches index.html ({len(hs)} inline scripts)")
        return
    OUT.write_text(text)
    print(f"_headers written; {len(hs)} inline script hashes")
    for h in hs:
        print("  " + h)


if __name__ == "__main__":
    main()
