#!/usr/bin/env python3
"""Build guide/index.html -- one file, captures embedded -- from guide/captures/*.png
and the text below. Regenerate with `make guide`; never hand-edit the output."""
import base64
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
CAP = ROOT / "guide" / "captures"
OUT = ROOT / "guide" / "index.html"

SECTIONS = [
    ("01-all-layers", "Open", "Fathom opens with every layer of the machine on one scrub bar: the program's source, the compiler's IR, the assembly, the register file, the pipeline, and — once loaded — the gates and the placed cells. The header names the machine: a three-stage RV32I core, synthesised to gates, mapped to Sky130 cells, placed and routed. It is a model of that core, not of the computer in front of you."),
    ("02-cycle-43", "Move through time", "Arrow keys step one cycle; shift steps ten; the scrub bar goes anywhere. Every layer moves together. Here at cycle 43 the first byte of “hi” is retiring: the source line that caused it, the instruction, the registers holding the byte and the UART address."),
    ("03-descend-source", "Descend from a line", "Click a source line, or press ↓, to descend. The line becomes the focus, the layer below opens as context, and the instrument jumps to the first cycle that line ran."),
    ("04-descend-asm", "…to the instruction", "Down again: the assembly in focus, the IR above and the register file below as context. The trail in the footer records each stop so the way back is exact."),
    ("05-descend-pipe", "…to the pipeline", "The pipeline: one column per cycle, one row per stage. Yellow is the instruction the descent follows; dim yellow is an instruction held in place — a taken branch or a load-use dependency — and red is a bubble with a named cause."),
    ("06-descend-gates", "…to the gates", "The bottom layers load on demand. The gate layer shows switching activity per cycle and, for the cycle in focus, which nets toggled."),
    ("07-descend-cells", "…to the placed cells", "The cells: every placed standard cell on the real die, dark; the ones switching this cycle, lit. Placed and routed on Sky130 — timing and DRC as reported in the artifact, not tape-out clean."),
    ("08-help", "Help", "? opens the help; it says what the machine is and is not, lists every key and click target, and names the agent face for anything that wants to drive the instrument programmatically."),
    ("09-popcount-branch-flush", "Another program", "The library has four programs, each chosen to show one thing: a call frame writing to a memory-mapped port, data-dependent branches, load-use stalls on a pointer walk, and a call across two compile units. This is popcount at a branch flush."),
]

def main():
    parts = []
    for name, title, text in SECTIONS:
        p = CAP / f"{name}.png"
        if not p.exists():
            raise SystemExit(f"missing capture {p.relative_to(ROOT)} -- run: make guide")
        b64 = base64.b64encode(p.read_bytes()).decode()
        parts.append(f'<section><h2>{title}</h2><p>{text}</p><img alt="{title}" src="data:image/png;base64,{b64}"></section>')
    html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Fathom — guide</title>
<style>
body{{margin:0;background:#101010;color:#e6e6e6;font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}}
main{{max-width:1100px;margin:0 auto;padding:24px}}h1{{font-size:20px;margin:0 0 4px}}h2{{font-size:15px;margin:32px 0 8px;color:#f2c14e}}
p{{color:#b4b4b4;max-width:72ch}}img{{width:100%;border:1px solid #2c2c2c;border-radius:2px;display:block}}
.sub{{color:#7a7a7a;font-size:12px}}nav{{margin:16px 0 0;font-size:12px}}nav a{{color:#7cc4ff;margin-right:12px}}
</style></head><body><main>
<h1>Fathom</h1><p class="sub">One event, followed down every layer of the machine, on one clock. A three-stage RV32I core, synthesised to gates, mapped to Sky130 cells, placed and routed.</p>
<nav>{' '.join(f'<a href="#s{i}">{t}</a>' for i, (_, t, _) in enumerate(SECTIONS))}</nav>
{''.join(f'<div id="s{i}">{s}</div>' for i, s in enumerate(parts))}
<p class="sub">Generated by forge/guide/build.py from guide/captures/. Regenerate; do not edit.</p>
</main></body></html>"""
    OUT.write_text(html)
    print(f"guide/index.html  {OUT.stat().st_size/1e6:.2f} MB  {len(parts)} sections")

if __name__ == "__main__":
    main()
